repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: [--select, E9,F821,B008]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: [-q, -ll]

  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.82.6
    hooks:
      - id: trufflehog
        args: ["filesystem", "--no-update", "--fail", "--entropy=False", "."]
