version: '3.9'
services:
  neo4j:
    image: neo4j:5.20
    ports: ["7474:7474","7687:7687"]
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
      NEO4J_PLUGINS: '[]'
    volumes:
      - neo4j_data:/data
  backend:
    build: ./backend
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      
    ports: ["8001:8001"]
    depends_on: [neo4j]
  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=http://backend:8001
    ports: ["5173:5173"]
    depends_on: [backend]
volumes:
  neo4j_data: {}
