name: CI (stabilise)

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    name: Backend (Python)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: idsideAI_FIXED
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps (soft)
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
          # ensure TestClient works even if FastAPI isn't pinned
          pip install fastapi pytest || true

      # 🔒 Strict: in-process health check (no ports, no flaky curl)
      - name: Healthz via TestClient (strict)
        run: PYTHONPATH=. python -c "from fastapi.testclient import TestClient; from idsideai.main import app; c=TestClient(app); r=c.get('/healthz'); print('status', r.status_code, 'body', r.text); import sys; sys.exit(0 if (r.status_code==200 and 'ok' in r.text.lower()) else 1)"

      - name: Upload backend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-ci-artifacts
          path: idsideAI_FIXED/requirements.txt
          if-no-files-found: ignore

  frontend:
    name: Frontend (Node)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Detect frontend directory
        id: detect
        shell: bash
        run: |
          if [ -f idsideAI_FIXED/frontend/package.json ]; then
            echo "dir=idsideAI_FIXED/frontend" >> "$GITHUB_OUTPUT"
            echo "havepkg=true" >> "$GITHUB_OUTPUT"
          else
            DIR=$(git ls-files | grep -E '^idsideAI_FIXED/.*/package.json$' | grep -v node_modules | head -n1 | xargs dirname || true)
            if [ -n "$DIR" ] && [ -f "$DIR/package.json" ]; then
              echo "dir=$DIR" >> "$GITHUB_OUTPUT"
              echo "havepkg=true" >> "$GITHUB_OUTPUT"
            else
              echo "dir=idsideAI_FIXED" >> "$GITHUB_OUTPUT"
              echo "havepkg=false" >> "$GITHUB_OUTPUT"
            fi
          fi

      - name: Install deps (soft)
        if: ${{ steps.detect.outputs.havepkg == 'true' }}
        working-directory: ${{ steps.detect.outputs.dir }}
        run: |
          if [ -f package-lock.json ]; then npm ci || true; else npm install || true; fi

      - name: Build (soft)
        if: ${{ steps.detect.outputs.havepkg == 'true' }}
        working-directory: ${{ steps.detect.outputs.dir }}
        run: |
          if npm run | grep -qE '^  build'; then npm run build || true; else echo "No build script; skipping."; fi

      - name: Upload build artifacts
        if: ${{ always() && steps.detect.outputs.havepkg == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: |
            ${{ steps.detect.outputs.dir }}/dist
            ${{ steps.detect.outputs.dir }}/build
          if-no-files-found: ignore
