name: CI

on:
  push:
    branches: ["main", "release/*"]
  pull_request:
    branches: ["main", "release/*"]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install basic tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy bandit pytest

      - name: Install project dependencies (safe if present)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ] || [ -f setup.cfg ]; then pip install -e . || true; fi

      - name: Ruff (non-blocking)
        run: ruff check . || true

      - name: Mypy (types, non-blocking)
        run: mypy . || true

      - name: Bandit (security, non-blocking)
        run: bandit -q -r . || true

      - name: Tests
        env:
          APP_ENV: ci
          OPENAI_API_KEY: "test"
        run: pytest -q
