name: CI

on:
  push:
    branches: ["main", "release/*"]
  pull_request:
    branches: ["main", "release/*"]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy bandit pytest

      # Try root requirements first (safe if not present)
      - name: Install root requirements (if any)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Install the app’s requirements from the subfolder (your tests live here)
      - name: Install app requirements (idsideAI_FIXED)
        working-directory: idsideAI_FIXED
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Failsafe: ensure core libs are available even if not pinned
          pip install fastapi uvicorn httpx pydantic || true

      # If the package is installable (pyproject.toml or setup.cfg), install it in editable mode
      - name: Install app package (editable, if defined)
        working-directory: idsideAI_FIXED
        run: |
          if [ -f pyproject.toml ] || [ -f setup.cfg ]; then pip install -e . || true; fi

      - name: Ruff (non-blocking)
        run: ruff check . || true

      - name: Mypy (non-blocking)
        run: mypy . || true

      - name: Bandit (non-blocking)
        run: bandit -q -r . || true

              # Ensure PYTHONPATH points to the app folder for imports
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}/idsideAI_FIXED" >> $GITHUB_ENV

      # Fix missing package markers (create __init__.py so Python sees packages)
      - name: Package sanity (idsideAI_FIXED)
        working-directory: idsideAI_FIXED
        run: |
          mkdir -p backend/middleware
          [ -f backend/__init__.py ] || printf '' > backend/__init__.py
          [ -f backend/middleware/__init__.py ] || printf '' > backend/middleware/__init__.py

      - name: Tests (run in idsideAI_FIXED)
        working-directory: idsideAI_FIXED
        env:
          APP_ENV: ci
          OPENAI_API_KEY: "test"
          PYTHONPATH: ${{ github.workspace }}/idsideAI_FIXED
        run: pytest -q

