name: CI

on:
  push:
    branches: [ ci-pipeline ]
  pull_request:

jobs:
  frontend:
    name: Frontend build (Vite)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: idsideAI_FIXED/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: idsideAI_FIXED/frontend/package-lock.json
      - run: npm ci
      - run: npm run build

  backend:
    name: Backend smoke (healthz)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: idsideAI_FIXED/backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install "fastapi>=0.112" "uvicorn[standard]>=0.30" "httpx" "pytest"
      - name: Healthz test (no server needed)
        run: |
          python - <<'PY'
          from app import app
          from fastapi.testclient import TestClient
          c = TestClient(app)
          r = c.get("/healthz")
          assert r.status_code == 200, r.text
          assert r.json().get("status") == "ok", r.json()
          print("healthz OK")
          PY
