name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install tooling & deps
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy bandit pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ] || [ -f setup.cfg ]; then pip install -e . || true; fi

      - name: Ruff
        run: ruff check .

      - name: Mypy (non-blocking)
        run: mypy . || true

      - name: Bandit (non-blocking)
        run: bandit -q -r . || true

      - name: Tests
        env:
          APP_ENV: ci
          OPENAI_API_KEY: "test"
        run: pytest -q || true
