name: Frontend (Node)

on:
  push:
    branches: ["main", "release/*"]
    paths:
      - "idsideAI_FIXED/frontend/**"
      - ".github/workflows/frontend.yml"
  pull_request:
    branches: ["main", "release/*"]
    paths:
      - "idsideAI_FIXED/frontend/**"
      - ".github/workflows/frontend.yml"
  workflow_dispatch:

jobs:
  frontend:
    name: Frontend (Node)
    runs-on: ubuntu-latest
    env:
      CI: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Detect fixed frontend path and set skip flag if missing
      - name: Verify frontend path
        id: verify
        shell: bash
        run: |
          set -euo pipefail
          if [ -f "idsideAI_FIXED/frontend/package.json" ]; then
            echo "FRONTEND_DIR=idsideAI_FIXED/frontend" >> "$GITHUB_ENV"
            echo "FRONTEND_SKIP=0" >> "$GITHUB_ENV"
            echo "Detected: idsideAI_FIXED/frontend/package.json"
          else
            echo "No package.json at idsideAI_FIXED/frontend — skipping frontend job."
            echo "FRONTEND_DIR=" >> "$GITHUB_ENV"
            echo "FRONTEND_SKIP=1" >> "$GITHUB_ENV"
          fi

      - name: Use Node.js
        if: env.FRONTEND_SKIP != '1'
        uses: actions/setup-node@v4
        with:
          node-version: "20"  # LTS

      - name: Enable Corepack (Yarn/Pnpm support)
        if: env.FRONTEND_SKIP != '1'
        run: corepack enable

      # Optional caches — only when lockfiles exist
      - name: Cache npm (if package-lock.json present)
        if: env.FRONTEND_SKIP != '1' && hashFiles('idsideAI_FIXED/frontend/package-lock.json') != ''
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-npm-${{ hashFiles('idsideAI_FIXED/frontend/package-lock.json', 'idsideAI_FIXED/frontend/npm-shrinkwrap.json') }}
          restore-keys: ${{ runner.os }}-node-npm-

      - name: Cache Yarn (if yarn.lock present)
        if: env.FRONTEND_SKIP != '1' && hashFiles('idsideAI_FIXED/frontend/yarn.lock') != ''
        uses: actions/cache@v4
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-node-yarn-${{ hashFiles('idsideAI_FIXED/frontend/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-yarn-

      - name: Show npm cache dir (diagnostic)
        if: env.FRONTEND_SKIP != '1'
        run: npm config get cache

      - name: Install dependencies
        if: env.FRONTEND_SKIP != '1'
        working-directory: ${{ env.FRONTEND_DIR }}
        shell: bash
        run: |
          set -euo pipefail
          if [ -f yarn.lock ]; then
            yarn install --immutable || yarn install
          else
            if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
              npm ci
            else
              npm install
            fi
          fi

      - name: Lint (non-blocking if script missing)
        if: env.FRONTEND_SKIP != '1'
        working-directory: ${{ env.FRONTEND_DIR }}
        run: npm run -s lint --if-present

      - name: Unit tests (non-blocking if script missing)
        if: env.FRONTEND_SKIP != '1'
        working-directory: ${{ env.FRONTEND_DIR }}
        run: npm run -s test --if-present

      - name: Type check (tsconfig only)
        if: env.FRONTEND_SKIP != '1' && hashFiles('idsideAI_FIXED/frontend/tsconfig.json') != ''
        working-directory: ${{ env.FRONTEND_DIR }}
        run: npx tsc --noEmit

      - name: Build (non-blocking if script missing)
        if: env.FRONTEND_SKIP != '1'
        working-directory: ${{ env.FRONTEND_DIR }}
        run: npm run -s build --if-present

      - name: Upload build artifact (optional)
        if: env.FRONTEND_SKIP != '1'
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: |
            idsideAI_FIXED/frontend/dist
            idsideAI_FIXED/frontend/build
          if-no-files-found: ignore

      - name: No frontend detected (informational)
        if: env.FRONTEND_SKIP == '1'
        run: echo "No frontend at idsideAI_FIXED/frontend; job completed successfully."
